Fix compilation error: replace ebiten.FileSystem with io/fs.FS
The ebiten.FileSystem type doesn't exist. Changed LoadCharacterTemplateFromFS
and LoadScreenFlowFromFS to use the standard io/fs.FS interface instead.